-- MySQL Script generated by MySQL Workbench
-- Mon May 14 02:11:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bt` DEFAULT CHARACTER SET utf8 ;
USE `bt` ;

-- -----------------------------------------------------
-- Table `bt`.`Flores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt`.`Flores` (
  `idFlores` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Stock` VARCHAR(45) NULL,
  `PrecioF` VARCHAR(45) NULL,
  PRIMARY KEY (`idFlores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt`.`Arreglos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt`.`Arreglos` (
  `idArreglos` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Caracterizacion` VARCHAR(45) NULL,
  `PrecioAr` VARCHAR(45) NULL,
  PRIMARY KEY (`idArreglos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt`.`Accersorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt`.`Accersorios` (
  `idAccersorios` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Material` VARCHAR(45) NULL,
  `Altura [cm]` VARCHAR(45) NULL,
  `Diametro boca [cm]` VARCHAR(45) NULL,
  `Stock` VARCHAR(45) NULL,
  `PrecioA` VARCHAR(45) NULL,
  PRIMARY KEY (`idAccersorios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt`.`Cactus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt`.`Cactus` (
  `idCactus` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Tamaño` VARCHAR(45) NULL,
  `Descripción` VARCHAR(45) NULL,
  `PrecioC` VARCHAR(45) NULL,
  PRIMARY KEY (`idCactus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt`.`Inventario Providencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt`.`Inventario Providencia` (
  `idInvProvidencia` INT NOT NULL,
  `Cantidad Inicial` INT NULL,
  `Cantidad Actual` INT NULL,
  `Accersorios_idAccersorios` INT NOT NULL,
  `Cactus_idCactus` INT NOT NULL,
  `Arreglos_idArreglos` INT NOT NULL,
  `Flores_idFlores` INT NOT NULL,
  PRIMARY KEY (`idInvProvidencia`, `Accersorios_idAccersorios`, `Cactus_idCactus`, `Arreglos_idArreglos`, `Flores_idFlores`),
  INDEX `fk_Inventario Providencia_Accersorios_idx` (`Accersorios_idAccersorios` ASC),
  INDEX `fk_Inventario Providencia_Cactus1_idx` (`Cactus_idCactus` ASC),
  INDEX `fk_Inventario Providencia_Arreglos1_idx` (`Arreglos_idArreglos` ASC),
  INDEX `fk_Inventario Providencia_Flores1_idx` (`Flores_idFlores` ASC),
  CONSTRAINT `fk_Inventario Providencia_Accersorios`
    FOREIGN KEY (`Accersorios_idAccersorios`)
    REFERENCES `bt`.`Accersorios` (`idAccersorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario Providencia_Cactus1`
    FOREIGN KEY (`Cactus_idCactus`)
    REFERENCES `bt`.`Cactus` (`idCactus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario Providencia_Arreglos1`
    FOREIGN KEY (`Arreglos_idArreglos`)
    REFERENCES `bt`.`Arreglos` (`idArreglos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario Providencia_Flores1`
    FOREIGN KEY (`Flores_idFlores`)
    REFERENCES `bt`.`Flores` (`idFlores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt`.`Inventario Providencia 2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt`.`Inventario Providencia 2` (
  `idInvProvidencia2` INT NOT NULL,
  `Cantidad Inicial` INT NULL,
  `Cantidad Actual` INT NULL,
  `Accersorios_idAccersorios` INT NOT NULL,
  `Cactus_idCactus` INT NOT NULL,
  `Arreglos_idArreglos` INT NOT NULL,
  `Flores_idFlores` INT NOT NULL,
  PRIMARY KEY (`idInvProvidencia2`, `Accersorios_idAccersorios`, `Cactus_idCactus`, `Arreglos_idArreglos`, `Flores_idFlores`),
  INDEX `fk_Inventario Providencia 2_Accersorios1_idx` (`Accersorios_idAccersorios` ASC),
  INDEX `fk_Inventario Providencia 2_Cactus1_idx` (`Cactus_idCactus` ASC),
  INDEX `fk_Inventario Providencia 2_Arreglos1_idx` (`Arreglos_idArreglos` ASC),
  INDEX `fk_Inventario Providencia 2_Flores1_idx` (`Flores_idFlores` ASC),
  CONSTRAINT `fk_Inventario Providencia 2_Accersorios1`
    FOREIGN KEY (`Accersorios_idAccersorios`)
    REFERENCES `bt`.`Accersorios` (`idAccersorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario Providencia 2_Cactus1`
    FOREIGN KEY (`Cactus_idCactus`)
    REFERENCES `bt`.`Cactus` (`idCactus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario Providencia 2_Arreglos1`
    FOREIGN KEY (`Arreglos_idArreglos`)
    REFERENCES `bt`.`Arreglos` (`idArreglos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario Providencia 2_Flores1`
    FOREIGN KEY (`Flores_idFlores`)
    REFERENCES `bt`.`Flores` (`idFlores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt`.`Inventario Nunoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt`.`Inventario Nunoa` (
  `idInvNunoa` INT NOT NULL,
  `Cantidad Inicial` INT NULL,
  `Cantidad Actual` INT NULL,
  `Accersorios_idAccersorios` INT NOT NULL,
  `Cactus_idCactus` INT NOT NULL,
  `Arreglos_idArreglos` INT NOT NULL,
  `Flores_idFlores` INT NOT NULL,
  PRIMARY KEY (`idInvNunoa`, `Accersorios_idAccersorios`, `Cactus_idCactus`, `Arreglos_idArreglos`, `Flores_idFlores`),
  INDEX `fk_Inventario Ñuñoa_Accersorios1_idx` (`Accersorios_idAccersorios` ASC),
  INDEX `fk_Inventario Ñuñoa_Cactus1_idx` (`Cactus_idCactus` ASC),
  INDEX `fk_Inventario Ñuñoa_Arreglos1_idx` (`Arreglos_idArreglos` ASC),
  INDEX `fk_Inventario Ñuñoa_Flores1_idx` (`Flores_idFlores` ASC),
  CONSTRAINT `fk_Inventario Ñuñoa_Accersorios1`
    FOREIGN KEY (`Accersorios_idAccersorios`)
    REFERENCES `bt`.`Accersorios` (`idAccersorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario Ñuñoa_Cactus1`
    FOREIGN KEY (`Cactus_idCactus`)
    REFERENCES `bt`.`Cactus` (`idCactus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario Ñuñoa_Arreglos1`
    FOREIGN KEY (`Arreglos_idArreglos`)
    REFERENCES `bt`.`Arreglos` (`idArreglos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario Ñuñoa_Flores1`
    FOREIGN KEY (`Flores_idFlores`)
    REFERENCES `bt`.`Flores` (`idFlores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt`.`Contenido Arreglo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt`.`Contenido Arreglo` (
  `idContenido Arreglo` INT NOT NULL,
  `Cantidad` INT NULL,
  `Flores_idFlores` INT NOT NULL,
  `Arreglos_idArreglos` INT NOT NULL,
  PRIMARY KEY (`idContenido Arreglo`, `Arreglos_idArreglos`),
  INDEX `fk_Contenido Arreglo_Flores1_idx` (`Flores_idFlores` ASC),
  INDEX `fk_Contenido Arreglo_Arreglos1_idx` (`Arreglos_idArreglos` ASC),
  CONSTRAINT `fk_Contenido Arreglo_Flores1`
    FOREIGN KEY (`Flores_idFlores`)
    REFERENCES `bt`.`Flores` (`idFlores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contenido Arreglo_Arreglos1`
    FOREIGN KEY (`Arreglos_idArreglos`)
    REFERENCES `bt`.`Arreglos` (`idArreglos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
