-- MySQL Script generated by MySQL Workbench
-- Tue May 15 01:20:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema intento3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema intento3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `intento3` DEFAULT CHARACTER SET utf8 ;
USE `intento3` ;

-- -----------------------------------------------------
-- Table `intento3`.`Flores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intento3`.`Flores` (
  `idFlores` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Stock` VARCHAR(45) NULL,
  `PrecioF` VARCHAR(45) NULL,
  PRIMARY KEY (`idFlores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intento3`.`Accesorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intento3`.`Accesorios` (
  `idAccesorios` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Material` VARCHAR(45) NULL,
  `Altura` VARCHAR(45) NULL,
  `DiametroBoca` VARCHAR(45) NULL,
  `Stock` VARCHAR(45) NULL,
  `PrecioA` VARCHAR(45) NULL,
  PRIMARY KEY (`idAccesorios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intento3`.`Arreglos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intento3`.`Arreglos` (
  `idArreglos` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Caracterizacion` VARCHAR(45) NULL,
  `PrecioAr` VARCHAR(45) NULL,
  PRIMARY KEY (`idArreglos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intento3`.`ContenidoArreglo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intento3`.`ContenidoArreglo` (
  `cantidadFlores` INT NOT NULL,
  `Arreglos_idArreglos` INT NOT NULL,
  `Flores_idFlores` INT NOT NULL,
  PRIMARY KEY (`cantidadFlores`, `Arreglos_idArreglos`),
  INDEX `fk_ContenidoArreglo_Arreglos1_idx` (`Arreglos_idArreglos` ASC),
  INDEX `fk_ContenidoArreglo_Flores1_idx` (`Flores_idFlores` ASC),
  CONSTRAINT `fk_ContenidoArreglo_Arreglos1`
    FOREIGN KEY (`Arreglos_idArreglos`)
    REFERENCES `intento3`.`Arreglos` (`idArreglos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ContenidoArreglo_Flores1`
    FOREIGN KEY (`Flores_idFlores`)
    REFERENCES `intento3`.`Flores` (`idFlores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intento3`.`Tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intento3`.`Tienda` (
  `idSucursales` INT NOT NULL,
  `NombreTienda` VARCHAR(45) NULL,
  PRIMARY KEY (`idSucursales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intento3`.`Mes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intento3`.`Mes` (
  `idMes` INT NOT NULL,
  `Mes` VARCHAR(45) NULL,
  PRIMARY KEY (`idMes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intento3`.`MovFlores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intento3`.`MovFlores` (
  `idMovFlores` INT NOT NULL,
  `CtdIngreso` VARCHAR(45) NULL,
  `CtdVenta` VARCHAR(45) NULL,
  `Mes_idMes` INT NOT NULL,
  `Flores_idFlores` INT NOT NULL,
  PRIMARY KEY (`idMovFlores`, `Mes_idMes`, `Flores_idFlores`),
  INDEX `fk_MovFlores_Mes1_idx` (`Mes_idMes` ASC),
  INDEX `fk_MovFlores_Flores1_idx` (`Flores_idFlores` ASC),
  CONSTRAINT `fk_MovFlores_Mes1`
    FOREIGN KEY (`Mes_idMes`)
    REFERENCES `intento3`.`Mes` (`idMes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MovFlores_Flores1`
    FOREIGN KEY (`Flores_idFlores`)
    REFERENCES `intento3`.`Flores` (`idFlores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intento3`.`MovAC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intento3`.`MovAC` (
  `idMovAC` INT NOT NULL,
  `CtdIngreso` VARCHAR(45) NULL,
  `CtdVenta` VARCHAR(45) NULL,
  `Mes_idMes` INT NOT NULL,
  `Accesorios_idAccesorios` INT NOT NULL,
  PRIMARY KEY (`idMovAC`, `Mes_idMes`, `Accesorios_idAccesorios`),
  INDEX `fk_MovAC_Mes1_idx` (`Mes_idMes` ASC),
  INDEX `fk_MovAC_Accesorios1_idx` (`Accesorios_idAccesorios` ASC),
  CONSTRAINT `fk_MovAC_Mes1`
    FOREIGN KEY (`Mes_idMes`)
    REFERENCES `intento3`.`Mes` (`idMes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MovAC_Accesorios1`
    FOREIGN KEY (`Accesorios_idAccesorios`)
    REFERENCES `intento3`.`Accesorios` (`idAccesorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intento3`.`MovAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intento3`.`MovAR` (
  `idMovAR` INT NOT NULL,
  `ctdIngreso` VARCHAR(45) NULL,
  `ctdVenta` VARCHAR(45) NULL,
  `Mes_idMes` INT NOT NULL,
  `Arreglos_idArreglos` INT NOT NULL,
  PRIMARY KEY (`idMovAR`, `Mes_idMes`, `Arreglos_idArreglos`),
  INDEX `fk_MovAR_Mes1_idx` (`Mes_idMes` ASC),
  INDEX `fk_MovAR_Arreglos1_idx` (`Arreglos_idArreglos` ASC),
  CONSTRAINT `fk_MovAR_Mes1`
    FOREIGN KEY (`Mes_idMes`)
    REFERENCES `intento3`.`Mes` (`idMes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MovAR_Arreglos1`
    FOREIGN KEY (`Arreglos_idArreglos`)
    REFERENCES `intento3`.`Arreglos` (`idArreglos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intento3`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intento3`.`Inventario` (
  `idInventario` INT NOT NULL,
  `ctdInicial` VARCHAR(45) NULL,
  `ctdFinal` VARCHAR(45) NULL,
  `Accesorios_idAccesorios` INT NOT NULL,
  `Flores_idFlores` INT NOT NULL,
  `Arreglos_idArreglos` INT NOT NULL,
  PRIMARY KEY (`idInventario`, `Accesorios_idAccesorios`, `Flores_idFlores`, `Arreglos_idArreglos`),
  INDEX `fk_Inventario_Accesorios1_idx` (`Accesorios_idAccesorios` ASC),
  INDEX `fk_Inventario_Flores1_idx` (`Flores_idFlores` ASC),
  INDEX `fk_Inventario_Arreglos1_idx` (`Arreglos_idArreglos` ASC),
  CONSTRAINT `fk_Inventario_Accesorios1`
    FOREIGN KEY (`Accesorios_idAccesorios`)
    REFERENCES `intento3`.`Accesorios` (`idAccesorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Flores1`
    FOREIGN KEY (`Flores_idFlores`)
    REFERENCES `intento3`.`Flores` (`idFlores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Arreglos1`
    FOREIGN KEY (`Arreglos_idArreglos`)
    REFERENCES `intento3`.`Arreglos` (`idArreglos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intento3`.`Tienda_has_MovFlores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intento3`.`Tienda_has_MovFlores` (
  `Tienda_idSucursales` INT NOT NULL,
  `MovFlores_idMovFlores` INT NOT NULL,
  PRIMARY KEY (`Tienda_idSucursales`, `MovFlores_idMovFlores`),
  INDEX `fk_Tienda_has_MovFlores_MovFlores1_idx` (`MovFlores_idMovFlores` ASC),
  INDEX `fk_Tienda_has_MovFlores_Tienda1_idx` (`Tienda_idSucursales` ASC),
  CONSTRAINT `fk_Tienda_has_MovFlores_Tienda1`
    FOREIGN KEY (`Tienda_idSucursales`)
    REFERENCES `intento3`.`Tienda` (`idSucursales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tienda_has_MovFlores_MovFlores1`
    FOREIGN KEY (`MovFlores_idMovFlores`)
    REFERENCES `intento3`.`MovFlores` (`idMovFlores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intento3`.`Tienda_has_MovAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intento3`.`Tienda_has_MovAR` (
  `Tienda_idSucursales` INT NOT NULL,
  `MovAR_idMovAR` INT NOT NULL,
  PRIMARY KEY (`Tienda_idSucursales`, `MovAR_idMovAR`),
  INDEX `fk_Tienda_has_MovAR_MovAR1_idx` (`MovAR_idMovAR` ASC),
  INDEX `fk_Tienda_has_MovAR_Tienda1_idx` (`Tienda_idSucursales` ASC),
  CONSTRAINT `fk_Tienda_has_MovAR_Tienda1`
    FOREIGN KEY (`Tienda_idSucursales`)
    REFERENCES `intento3`.`Tienda` (`idSucursales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tienda_has_MovAR_MovAR1`
    FOREIGN KEY (`MovAR_idMovAR`)
    REFERENCES `intento3`.`MovAR` (`idMovAR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intento3`.`Tienda_has_MovAC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intento3`.`Tienda_has_MovAC` (
  `Tienda_idSucursales` INT NOT NULL,
  `MovAC_idMovAC` INT NOT NULL,
  PRIMARY KEY (`Tienda_idSucursales`, `MovAC_idMovAC`),
  INDEX `fk_Tienda_has_MovAC_MovAC1_idx` (`MovAC_idMovAC` ASC),
  INDEX `fk_Tienda_has_MovAC_Tienda1_idx` (`Tienda_idSucursales` ASC),
  CONSTRAINT `fk_Tienda_has_MovAC_Tienda1`
    FOREIGN KEY (`Tienda_idSucursales`)
    REFERENCES `intento3`.`Tienda` (`idSucursales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tienda_has_MovAC_MovAC1`
    FOREIGN KEY (`MovAC_idMovAC`)
    REFERENCES `intento3`.`MovAC` (`idMovAC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
